### ISSUE TITLE
Add access to model object?

### ISSUE THREAD

**Issue by ColCarroll** [mggg/ecological-inference#5]
It might be nice to have access to the internal pymc3 model (where available). I specifically want to be able to use `pm.model_to_graphviz` in a notebook and get a graphical model of what is going on.

**Comment by karink520** [comment]
Done. You can now access the model with, e.g., ei.sim_model. I also added a line showing how to use this with pm.model_to_graphviz to the demo notebooks. Thanks for suggesting!
