### ISSUE TITLE
Expanding introduction at beginning of README

### ISSUE THREAD

**Issue by matt-graham** [mggg/ecological-inference#61]
Submitting as part of JOSS review openjournals/joss-reviews#3397

While the introduction notebooks do give a good summary of what problems the software is designed to solve and who the target audience is, the introduction at the beginning of the README file is currently a bit lacking in detail. I would suggest adding a couple of sentences defining what ecological inference is  and what functionality PyEI offers.

**Comment by pmyteh** [comment]
Agreed. The brief description at the top of the paper is very good and could usefully be repurposed.
