### ISSUE TITLE
`lint_and_test.sh` script not running tests

### ISSUE THREAD

**Issue by matt-graham** [mggg/ecological-inference#64]
Submitting as part of JOSS review openjournals/joss-reviews#3397

The script `scripts/lint_and_test.sh` currently does not run the tests on my machine (running code as of  2d47262e413a4e17db1eead0924cff164e57f01b on Ubuntu 20.04). It seems that the `pylint` check may be returning an error status which due to the `set -ex` call then causes the script to exit without running the `scripts/test.sh` script. Running `scripts/test.sh` directly works however.

**Comment by karink520** [comment]
Ah, thanks! Looks like pylint shifted under us, so we hadn't been seeing this error before. Will update.
