### ISSUE TITLE
Small comment change

### ISSUE THREAD

**Issue by mitch-at-orika** [mggg/ecological-inference#91]
**very minor issue** 

I am working through how this package works and I think this comment is referencing the wrong dimension??

[`shape=(num_precincts, num_rows),num_precincts x r`](https://github.com/mggg/ecological-inference/blob/425e47416dc3247e3ca49768f54bb4ca2c958fdc/pyei/r_by_c_models.py#L61-L62)

edit:
maybe it is more than just the comment and the input to the shape of multinomial also?

is this meant to be # num_precincts x c ?? I think that the sum(axis=1) in previous line is summing out r (groups_fraction) and leaving c(votes)?? I could be wrong and missing something.

Thanks for this library btw, the general version of this problem is something I've been seeking a pymc/bayes solution to for a long time. In my journey I've made an example notebook that adds another dummy candidate in so the position of the votes fraction axis is more clear for people trying to understand it so its 42 x 3 x 4 not 42 x 3 x 3. Let me know if you want PR with that notebook in the examples.

**Comment by mitch-at-orika** [comment]
hmm it is crazy I ran my test with 4 candidates and ran the model with:
`    pm.Multinomial(
        "votes_count",
        n=precinct_pops,
        p=theta,
        observed=votes_count_obs,
        shape=(num_precincts, num_rows),
    )  # num_precincts x r`

but when send model to graphviz and review the trace it doesn't listen and overwrites the shape to 42 x 4 (even though num_rows=3!!). pm.Multinomial must just use the shape of votes_count_obs or theta and ignore the shape input?? 

I also noticed that there was another issue that might be related?? #52

**Comment by karink520** [comment]
Sorry for the slow reply here! Let me take a look in the next day or so and get back to you. We changed versions of pymc3 with our most recent update so it's possible that's related. Thanks for bringing this up!

An example notebook with the 42x3x4 example would be a welcome addition!
